# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/main/limen

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/main/limen

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/main/limen/CMakeFiles /home/main/limen//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/main/limen/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named limen_devinfo

# Build rule for target.
limen_devinfo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 limen_devinfo
.PHONY : limen_devinfo

# fast build rule for target.
limen_devinfo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/limen_devinfo.dir/build.make CMakeFiles/limen_devinfo.dir/build
.PHONY : limen_devinfo/fast

#=============================================================================
# Target rules for targets named limen_connect

# Build rule for target.
limen_connect: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 limen_connect
.PHONY : limen_connect

# fast build rule for target.
limen_connect/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/limen_connect.dir/build.make CMakeFiles/limen_connect.dir/build
.PHONY : limen_connect/fast

src/limen_common.o: src/limen_common.cpp.o
.PHONY : src/limen_common.o

# target to build an object file
src/limen_common.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/limen_connect.dir/build.make CMakeFiles/limen_connect.dir/src/limen_common.cpp.o
.PHONY : src/limen_common.cpp.o

src/limen_common.i: src/limen_common.cpp.i
.PHONY : src/limen_common.i

# target to preprocess a source file
src/limen_common.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/limen_connect.dir/build.make CMakeFiles/limen_connect.dir/src/limen_common.cpp.i
.PHONY : src/limen_common.cpp.i

src/limen_common.s: src/limen_common.cpp.s
.PHONY : src/limen_common.s

# target to generate assembly for a file
src/limen_common.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/limen_connect.dir/build.make CMakeFiles/limen_connect.dir/src/limen_common.cpp.s
.PHONY : src/limen_common.cpp.s

src/limen_connect.o: src/limen_connect.cpp.o
.PHONY : src/limen_connect.o

# target to build an object file
src/limen_connect.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/limen_connect.dir/build.make CMakeFiles/limen_connect.dir/src/limen_connect.cpp.o
.PHONY : src/limen_connect.cpp.o

src/limen_connect.i: src/limen_connect.cpp.i
.PHONY : src/limen_connect.i

# target to preprocess a source file
src/limen_connect.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/limen_connect.dir/build.make CMakeFiles/limen_connect.dir/src/limen_connect.cpp.i
.PHONY : src/limen_connect.cpp.i

src/limen_connect.s: src/limen_connect.cpp.s
.PHONY : src/limen_connect.s

# target to generate assembly for a file
src/limen_connect.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/limen_connect.dir/build.make CMakeFiles/limen_connect.dir/src/limen_connect.cpp.s
.PHONY : src/limen_connect.cpp.s

src/limen_devinfo.o: src/limen_devinfo.cpp.o
.PHONY : src/limen_devinfo.o

# target to build an object file
src/limen_devinfo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/limen_devinfo.dir/build.make CMakeFiles/limen_devinfo.dir/src/limen_devinfo.cpp.o
.PHONY : src/limen_devinfo.cpp.o

src/limen_devinfo.i: src/limen_devinfo.cpp.i
.PHONY : src/limen_devinfo.i

# target to preprocess a source file
src/limen_devinfo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/limen_devinfo.dir/build.make CMakeFiles/limen_devinfo.dir/src/limen_devinfo.cpp.i
.PHONY : src/limen_devinfo.cpp.i

src/limen_devinfo.s: src/limen_devinfo.cpp.s
.PHONY : src/limen_devinfo.s

# target to generate assembly for a file
src/limen_devinfo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/limen_devinfo.dir/build.make CMakeFiles/limen_devinfo.dir/src/limen_devinfo.cpp.s
.PHONY : src/limen_devinfo.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... limen_connect"
	@echo "... limen_devinfo"
	@echo "... src/limen_common.o"
	@echo "... src/limen_common.i"
	@echo "... src/limen_common.s"
	@echo "... src/limen_connect.o"
	@echo "... src/limen_connect.i"
	@echo "... src/limen_connect.s"
	@echo "... src/limen_devinfo.o"
	@echo "... src/limen_devinfo.i"
	@echo "... src/limen_devinfo.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

