#ifndef limen_common
#define limen_common
#include <stdint.h>
#include <infiniband/verbs.h>
#include <string>
#include <format>

//#define EXIT_SUCCESS (0) already defined
#define EXIT_USAGE_ERROR (1)
#define EXIT_DEVICE_ERROR (2)
#define EXIT_VERB_ERROR (3)
#define EXIT_SIDE_CHANNEL_ERROR (4)


// parses out a uint64_t value into val_addr; returns 0 on success and 1 on failure
int parse_u64_strict(const char* str, uint64_t* val_addr);

// parses out a int value into val_addr; returns 0 on success and 1 on failure
int parse_int_strict(const char* str, int* val_addr);

//  returns the index of the first ibv_device whose name 
//  matches device_name; returns -1 if not found
int find_device_by_name(ibv_device** devices_list, const char* device_name);

//  todo docstring
void print_device_info(ibv_device_attr* attr);

//  todo docstring
void print_port_info(ibv_port_attr* attr);

//  todo docstring
std::string gid_to_str(ibv_gid* gid);

//  takes a std::string generated by gid_to_str & packs gid with its values; return 0 on success 1 on fail
int str_to_gid(std::string str, ibv_gid* gid);


#endif