#pragma once
#define EXIT_USAGE_ERROR (1)
#define EXIT_DEVICE_ERROR (2)
#define EXIT_VERB_ERROR (3)
#define EXIT_SIDE_CHANNEL_ERROR (4)
#define EXIT_COMPLETION_STATUS_ERROR (5)
#define EXIT_PAYLOAD_VERIFICATION_ERROR (6)
#define EXIT_CONNECTION_MANAGER_FAILURE (7)